-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 10:29:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema climbing_gear
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema climbing_gear
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climbing_gear` DEFAULT CHARACTER SET utf8 ;
USE `climbing_gear` ;

-- -----------------------------------------------------
-- Table `climbing_gear`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_gear`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing_gear`.`gear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_gear`.`gear` (
  `gear_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1023) NOT NULL,
  `brand` VARCHAR(128) NOT NULL,
  `weight_grams` INT NULL,
  `length_mm` INT NULL,
  `width_mm` INT NULL,
  `depth_mm` INT NULL,
  `locking` TINYINT NULL,
  PRIMARY KEY (`gear_id`, `category_id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `climbing_gear`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing_gear`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_gear`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing_gear`.`user_gear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_gear`.`user_gear` (
  `user_id` INT NOT NULL,
  `gear_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `gear_id_idx` (`gear_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `gear_id`),
  CONSTRAINT `gear_id`
    FOREIGN KEY (`gear_id`)
    REFERENCES `climbing_gear`.`gear` (`gear_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `climbing_gear`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
